version: '3'

networks:
  randao:

services:
  randao-participant0:
    image: findoranetwork/randao:v0.1.0
    container_name: participant0
    restart: always
    environment:
      - KEYSTORE_PASSWORD=pswd0
    command: --config /config/config.json
    volumes:
      - ./campaigns/participant0:/root/.randao
      - ./config/config0.json:/config/config.json
      - ./keys/0x02a5D1F97c24dC9399A2878dc44cbDA274093B6D.key:/keys/0x02a5D1F97c24dC9399A2878dc44cbDA274093B6D.key
    networks:
      - randao
  randao-participant1:
    image: findoranetwork/randao:v0.1.0
    container_name: participant1
    restart: always
    environment:
      - KEYSTORE_PASSWORD=pswd1
    command: --config /config/config.json
    volumes:
      - ./campaigns/participant1:/root/.randao
      - ./config/config1.json:/config/config.json
      - ./keys/0xf016802048A95017bAa7670c944D23537b2b2F19.key:/keys/0xf016802048A95017bAa7670c944D23537b2b2F19.key
    networks:
      - randao
  randao-participant2:
    image: findoranetwork/randao:v0.1.0
    container_name: participant2
    restart: always
    environment:
      - KEYSTORE_PASSWORD=pswd2
    command: --config /config/config.json
    volumes:
      - ./campaigns/participant2:/root/.randao
      - ./config/config2.json:/config/config.json
      - ./keys/0xAB9F918fBefE4b6C9464774F06482DEf349579EF.key:/keys/0xAB9F918fBefE4b6C9464774F06482DEf349579EF.key
    networks:
      - randao
